name: Deploy

on:
  push:
    branches:
      - develop
      - staging
      - main

permissions:
  deployments: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set environment name
        id: set_env
        run: |
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "env_name=qa" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            echo "env_name=stage" >> $GITHUB_OUT